### ISSUE TITLE
TYDOT speaking~~~

### ISSUE THREAD

**Issue by WealthyElk** [Lytsu/lowlight#6]
Hi there Rytsu,

May I have the honor of meeting you in QQ and stuff? Please solve this issue ASAP thanksss.

Sincerely,
TDKUAN.

**Comment by Lytsu** [comment]
Hi, Rytsu here.

For some reasons, I won't provide any personal contact IMs, including QQ and Telegram. You can still contact me through the contact info on the site.

And please remember that, you should use GitHub Issues to report ideas, feedback, or bugs for work on this project. It **IS NOT** a comment section.

Sincerely,
Rytsu.
