### ISSUE TITLE
关于daisu.ke相关事宜

### ISSUE THREAD

**Issue by kevinluo6191** [Lytsu/lowlight#7]
daisu.ke的证书过期了(

**Comment by Lytsu** [comment]
实际上 daisu.ke 这个域名以及其 SSL 证书是 Maverick 的，而不是我的。
前几天这个证书就过期了，但由于证书注册商疑似跑路，所以没办法续费；同时由于之前那个证书绑定的域名太多， Maverick 就只修复了 *.616.sb 的证书……
我这边没什么办法处理这事，只能等他修复了……
